project:
  type: website
  output-dir: _site
  resources:
    - "assets/"

website:
  title: "Your Site Title"
  navbar:
    background: secondary
    search: true
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    html: true
    theme: sandstone
    highlight-style: atom-one
    css: assets/css/styles.css
