project:
  type: website
  title: "codeandcircuits.com"
  output-dir: _site
  resources:
    - "assets/"
  render:
    - "*.qmd"
    - "posts/**/*.qmd"

website:
  title: "codeandcircuits.com"
  favicon: assets/images/favicon.png
  navbar:
    background: secondary
    search: true
    logo: assets/images/header-logo-fixed.png
    logo-width: 300px
    logo-alt: "Site logo"
    title: false
    left:
      - text: "Home"
        href: index.qmd
  site-url: "https://codeandcircuits.com"

format:
  html:
    html: true
    theme: sandstone
    highlight-style: atom-one
    css: assets/css/styles.css
