project:
  type: website
  title: "codeandcircuits.com"
  output-dir: _site
  resources:
    - "assets/"
    - "CNAME"
  render:
    - "*.qmd"
    - "posts/**/*.qmd"

website:
  title: "Code & Circuits"
  favicon: assets/images/favicon.png
  navbar:
    background: secondary
    search: true
    logo: assets/images/header-logo-fixed.png
    logo-width: 300px
    logo-alt: "Site logo"
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Posts
      - href: notebooks/index.qmd
        text: Notebooks
      - href: about/index.qmd
        text: About
  site-url: "https://codeandcircuits.com"

format:
  html:
    html: true
    theme: cosmo
    highlight-style: atom-one
    css: assets/css/styles.css
